# Generated by Django 3.2.11 on 2023-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_asking',
            field=models.BooleanField(default=False),
        ),
    ]
