# Generated by Django 3.2.11 on 2023-05-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0002_message_is_asking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_propmted', models.BooleanField(default=False)),
            ],
        ),
    ]
