# Generated by Django 3.2.11 on 2023-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0003_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, primary_key='True', serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
